### ISSUE TITLE
Algumas coisas sem tradução no UI_PTBR

### ISSUE THREAD

**Issue by Liebelts** [rodrigomantoan/projectzomboid-translation#6]
Eu achei algumas coisas sem tradução no arquivo UI_PTBR então decidi traduzir elas.

Textos sem tradução:
![image](https://user-images.githubusercontent.com/42952107/49475423-55522200-f7fe-11e8-8b79-0dadcadaa350.png)

Arquivo traduzido:
[UI_PTBR nova.txt](https://github.com/rodrigomantoan/projectzomboid-translation/files/2646453/UI_PTBR.nova.txt)

**Comment by JohnySouzac** [comment]
Implementado :D
