### ISSUE TITLE
Revisão parcial da v9.1/9.2

### ISSUE THREAD

**Issue by Liebelts** [rodrigomantoan/projectzomboid-translation#7]
Corrigi alguns erros de escrita, acentuação etc. da última versão

Arquivos revisados:

- ContextMenu_PTBR
- Farming_PTBR
- GameSound_PTBR
- Items_PTBR
- Moodles_PTBR
- Moveables_PTBR
- MultiStageBuild_PTBR
- News_PTBR
- Recipes_PTBR
- Sandbox_PTBR
- Stash_PTBR

[Lista dos erros](https://pastebin.com/XSdXQzgK)

[Arquivos corrigidos](https://github.com/rodrigomantoan/projectzomboid-translation/files/2650158/Correcoes.da.traducao.9.1.zip)

**Comment by CavemanDuMa** [comment]
Corrigidos!
